[tools]
bun = "latest"
helm = "latest"
rust = "latest"
"aqua:supabase/cli" = "latest"
"github:ahmetb/kubectl-tree" = "latest"
"github:ahmetb/kubectx" = "latest"
"github:ajeetdsouza/zoxide" = "latest"
"github:astral-sh/uv" = "latest"
"github:atuinsh/atuin" = "latest"
"github:derailed/k9s" = "latest"
"github:eza-community/eza" = "latest"
"github:fluxcd/flux2" = "latest"
"github:helm-unittest/helm-unittest" = "latest"
"github:junegunn/fzf" = "latest"
"github:keisku/kubectl-explore" = "latest"
"github:sl1pm4t/k2tf" = "latest"
"github:sharkdp/bat" = "latest"
"github:sharkdp/fd" = "latest"
"github:twpayne/chezmoi" = "latest"
"github:vicinaehq/vicinae" = "latest"
"github:zellij-org/zellij" = "latest"
